// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjbvtltfyzbujdkkhnbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqYnZ0bHRmeXpidWpka2tobmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTMxMTQsImV4cCI6MjA2NTQ2OTExNH0.pLj0h5OS8jx1FyhSO-0Bp4RM9gdP4EHYRxvttHmVXLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);